services:
  duckdb:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DUCKDB_VERSION: v1.1.3
    image: duckdb-local:1.1.3
    container_name: duckdb
    tty: true
    stdin_open: true
    volumes:
      - ./data:/data
      - ./provision/home/.dbt:/home/duck/.dbt
      - ./provision/dbt-projects/hello-duck:/data/hello-duck
    working_dir: /data
